### ISSUE TITLE
Additional Data

### ISSUE THREAD

**Issue by jasperchua99** [wgumenyuk/msn-weather#3]
Hi can i ask will everything in the Weatherforecast in the documentation here be included?
https://docs.microsoft.com/en-us/connectors/msnweather/#weatherforecast

**Comment by wgumenyuk** [comment]
Hi there, thanks for opening this issue! Unfortunately, the link you provided does not seem to correspond to the API endpoint used in this library (https://weather.service.msn.com/find.aspx). This means that I'm not able to implement this data.

**Comment by jasperchua99** [comment]
Oic, so all these here will be included?
![Screenshot_20220808-062349](https://user-images.githubusercontent.com/30612883/183313321-8ab44c6b-d9f9-4ba9-bfa5-14b52b975d36.png)

**Comment by jasperchua99** [comment]
Cos

https://docs.microsoft.com/en-us/sharepoint/troubleshoot/apps/msn-weather-service-api-retired

**Comment by wgumenyuk** [comment]
> https://docs.microsoft.com/en-us/sharepoint/troubleshoot/apps/msn-weather-service-api-retired

The newer MSN Weather API seems to only work within the constraints of [Microsoft PowerApps](https://docs.microsoft.com/en-us/power-apps/powerapps-overview).

Although the MSN Weather API is considered discontinued, it still provides reliable data (notice the different endpoint, `data.aspx` vs. `find.aspx` used in this library).

I don't plan to adapt this library to other / newer APIs and add more weather data.

For a list of all weather data that this library provides, please see https://github.com/wgumenyuk/msn-weather#retrieved-data-format.
